// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMsg.proto

#ifndef PROTOBUF_BaseMsg_2eproto__INCLUDED
#define PROTOBUF_BaseMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace zhu {
class ErrorMessage;
class ErrorMessageDefaultTypeInternal;
extern ErrorMessageDefaultTypeInternal _ErrorMessage_default_instance_;
class SelfDescribingMessage;
class SelfDescribingMessageDefaultTypeInternal;
extern SelfDescribingMessageDefaultTypeInternal _SelfDescribingMessage_default_instance_;
}  // namespace zhu

namespace zhu {

namespace protobuf_BaseMsg_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_BaseMsg_2eproto

// ===================================================================

class SelfDescribingMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zhu.SelfDescribingMessage) */ {
 public:
  SelfDescribingMessage();
  virtual ~SelfDescribingMessage();

  SelfDescribingMessage(const SelfDescribingMessage& from);

  inline SelfDescribingMessage& operator=(const SelfDescribingMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SelfDescribingMessage& default_instance();

  static inline const SelfDescribingMessage* internal_default_instance() {
    return reinterpret_cast<const SelfDescribingMessage*>(
               &_SelfDescribingMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SelfDescribingMessage* other);

  // implements Message ----------------------------------------------

  inline SelfDescribingMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  SelfDescribingMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SelfDescribingMessage& from);
  void MergeFrom(const SelfDescribingMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SelfDescribingMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 socket = 2;
  int socket_size() const;
  void clear_socket();
  static const int kSocketFieldNumber = 2;
  ::google::protobuf::int32 socket(int index) const;
  void set_socket(int index, ::google::protobuf::int32 value);
  void add_socket(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      socket() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_socket();

  // required bytes type_name = 1;
  bool has_type_name() const;
  void clear_type_name();
  static const int kTypeNameFieldNumber = 1;
  const ::std::string& type_name() const;
  void set_type_name(const ::std::string& value);
  #if LANG_CXX11
  void set_type_name(::std::string&& value);
  #endif
  void set_type_name(const char* value);
  void set_type_name(const void* value, size_t size);
  ::std::string* mutable_type_name();
  ::std::string* release_type_name();
  void set_allocated_type_name(::std::string* type_name);

  // required bytes message_data = 3;
  bool has_message_data() const;
  void clear_message_data();
  static const int kMessageDataFieldNumber = 3;
  const ::std::string& message_data() const;
  void set_message_data(const ::std::string& value);
  #if LANG_CXX11
  void set_message_data(::std::string&& value);
  #endif
  void set_message_data(const char* value);
  void set_message_data(const void* value, size_t size);
  ::std::string* mutable_message_data();
  ::std::string* release_message_data();
  void set_allocated_message_data(::std::string* message_data);

  // @@protoc_insertion_point(class_scope:zhu.SelfDescribingMessage)
 private:
  void set_has_type_name();
  void clear_has_type_name();
  void set_has_message_data();
  void clear_has_message_data();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > socket_;
  ::google::protobuf::internal::ArenaStringPtr type_name_;
  ::google::protobuf::internal::ArenaStringPtr message_data_;
  friend struct protobuf_BaseMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ErrorMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zhu.ErrorMessage) */ {
 public:
  ErrorMessage();
  virtual ~ErrorMessage();

  ErrorMessage(const ErrorMessage& from);

  inline ErrorMessage& operator=(const ErrorMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ErrorMessage& default_instance();

  static inline const ErrorMessage* internal_default_instance() {
    return reinterpret_cast<const ErrorMessage*>(
               &_ErrorMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ErrorMessage* other);

  // implements Message ----------------------------------------------

  inline ErrorMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  ErrorMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ErrorMessage& from);
  void MergeFrom(const ErrorMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ErrorMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes desc = 2;
  bool has_desc() const;
  void clear_desc();
  static const int kDescFieldNumber = 2;
  const ::std::string& desc() const;
  void set_desc(const ::std::string& value);
  #if LANG_CXX11
  void set_desc(::std::string&& value);
  #endif
  void set_desc(const char* value);
  void set_desc(const void* value, size_t size);
  ::std::string* mutable_desc();
  ::std::string* release_desc();
  void set_allocated_desc(::std::string* desc);

  // optional int32 id = 1 [default = -1];
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:zhu.ErrorMessage)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_desc();
  void clear_has_desc();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr desc_;
  ::google::protobuf::int32 id_;
  friend struct protobuf_BaseMsg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SelfDescribingMessage

// required bytes type_name = 1;
inline bool SelfDescribingMessage::has_type_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SelfDescribingMessage::set_has_type_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SelfDescribingMessage::clear_has_type_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SelfDescribingMessage::clear_type_name() {
  type_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type_name();
}
inline const ::std::string& SelfDescribingMessage::type_name() const {
  // @@protoc_insertion_point(field_get:zhu.SelfDescribingMessage.type_name)
  return type_name_.GetNoArena();
}
inline void SelfDescribingMessage::set_type_name(const ::std::string& value) {
  set_has_type_name();
  type_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zhu.SelfDescribingMessage.type_name)
}
#if LANG_CXX11
inline void SelfDescribingMessage::set_type_name(::std::string&& value) {
  set_has_type_name();
  type_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zhu.SelfDescribingMessage.type_name)
}
#endif
inline void SelfDescribingMessage::set_type_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_type_name();
  type_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zhu.SelfDescribingMessage.type_name)
}
inline void SelfDescribingMessage::set_type_name(const void* value, size_t size) {
  set_has_type_name();
  type_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zhu.SelfDescribingMessage.type_name)
}
inline ::std::string* SelfDescribingMessage::mutable_type_name() {
  set_has_type_name();
  // @@protoc_insertion_point(field_mutable:zhu.SelfDescribingMessage.type_name)
  return type_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SelfDescribingMessage::release_type_name() {
  // @@protoc_insertion_point(field_release:zhu.SelfDescribingMessage.type_name)
  clear_has_type_name();
  return type_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SelfDescribingMessage::set_allocated_type_name(::std::string* type_name) {
  if (type_name != NULL) {
    set_has_type_name();
  } else {
    clear_has_type_name();
  }
  type_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type_name);
  // @@protoc_insertion_point(field_set_allocated:zhu.SelfDescribingMessage.type_name)
}

// repeated int32 socket = 2;
inline int SelfDescribingMessage::socket_size() const {
  return socket_.size();
}
inline void SelfDescribingMessage::clear_socket() {
  socket_.Clear();
}
inline ::google::protobuf::int32 SelfDescribingMessage::socket(int index) const {
  // @@protoc_insertion_point(field_get:zhu.SelfDescribingMessage.socket)
  return socket_.Get(index);
}
inline void SelfDescribingMessage::set_socket(int index, ::google::protobuf::int32 value) {
  socket_.Set(index, value);
  // @@protoc_insertion_point(field_set:zhu.SelfDescribingMessage.socket)
}
inline void SelfDescribingMessage::add_socket(::google::protobuf::int32 value) {
  socket_.Add(value);
  // @@protoc_insertion_point(field_add:zhu.SelfDescribingMessage.socket)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SelfDescribingMessage::socket() const {
  // @@protoc_insertion_point(field_list:zhu.SelfDescribingMessage.socket)
  return socket_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SelfDescribingMessage::mutable_socket() {
  // @@protoc_insertion_point(field_mutable_list:zhu.SelfDescribingMessage.socket)
  return &socket_;
}

// required bytes message_data = 3;
inline bool SelfDescribingMessage::has_message_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SelfDescribingMessage::set_has_message_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SelfDescribingMessage::clear_has_message_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SelfDescribingMessage::clear_message_data() {
  message_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_message_data();
}
inline const ::std::string& SelfDescribingMessage::message_data() const {
  // @@protoc_insertion_point(field_get:zhu.SelfDescribingMessage.message_data)
  return message_data_.GetNoArena();
}
inline void SelfDescribingMessage::set_message_data(const ::std::string& value) {
  set_has_message_data();
  message_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zhu.SelfDescribingMessage.message_data)
}
#if LANG_CXX11
inline void SelfDescribingMessage::set_message_data(::std::string&& value) {
  set_has_message_data();
  message_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zhu.SelfDescribingMessage.message_data)
}
#endif
inline void SelfDescribingMessage::set_message_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_message_data();
  message_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zhu.SelfDescribingMessage.message_data)
}
inline void SelfDescribingMessage::set_message_data(const void* value, size_t size) {
  set_has_message_data();
  message_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zhu.SelfDescribingMessage.message_data)
}
inline ::std::string* SelfDescribingMessage::mutable_message_data() {
  set_has_message_data();
  // @@protoc_insertion_point(field_mutable:zhu.SelfDescribingMessage.message_data)
  return message_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SelfDescribingMessage::release_message_data() {
  // @@protoc_insertion_point(field_release:zhu.SelfDescribingMessage.message_data)
  clear_has_message_data();
  return message_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SelfDescribingMessage::set_allocated_message_data(::std::string* message_data) {
  if (message_data != NULL) {
    set_has_message_data();
  } else {
    clear_has_message_data();
  }
  message_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message_data);
  // @@protoc_insertion_point(field_set_allocated:zhu.SelfDescribingMessage.message_data)
}

// -------------------------------------------------------------------

// ErrorMessage

// optional int32 id = 1 [default = -1];
inline bool ErrorMessage::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ErrorMessage::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ErrorMessage::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ErrorMessage::clear_id() {
  id_ = -1;
  clear_has_id();
}
inline ::google::protobuf::int32 ErrorMessage::id() const {
  // @@protoc_insertion_point(field_get:zhu.ErrorMessage.id)
  return id_;
}
inline void ErrorMessage::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:zhu.ErrorMessage.id)
}

// optional bytes desc = 2;
inline bool ErrorMessage::has_desc() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ErrorMessage::set_has_desc() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ErrorMessage::clear_has_desc() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ErrorMessage::clear_desc() {
  desc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_desc();
}
inline const ::std::string& ErrorMessage::desc() const {
  // @@protoc_insertion_point(field_get:zhu.ErrorMessage.desc)
  return desc_.GetNoArena();
}
inline void ErrorMessage::set_desc(const ::std::string& value) {
  set_has_desc();
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zhu.ErrorMessage.desc)
}
#if LANG_CXX11
inline void ErrorMessage::set_desc(::std::string&& value) {
  set_has_desc();
  desc_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zhu.ErrorMessage.desc)
}
#endif
inline void ErrorMessage::set_desc(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_desc();
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zhu.ErrorMessage.desc)
}
inline void ErrorMessage::set_desc(const void* value, size_t size) {
  set_has_desc();
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zhu.ErrorMessage.desc)
}
inline ::std::string* ErrorMessage::mutable_desc() {
  set_has_desc();
  // @@protoc_insertion_point(field_mutable:zhu.ErrorMessage.desc)
  return desc_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ErrorMessage::release_desc() {
  // @@protoc_insertion_point(field_release:zhu.ErrorMessage.desc)
  clear_has_desc();
  return desc_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ErrorMessage::set_allocated_desc(::std::string* desc) {
  if (desc != NULL) {
    set_has_desc();
  } else {
    clear_has_desc();
  }
  desc_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), desc);
  // @@protoc_insertion_point(field_set_allocated:zhu.ErrorMessage.desc)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace zhu

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BaseMsg_2eproto__INCLUDED
